title: Alastair McBride
email: amcb.home@gmail.com
description: >
  Dedicated professional with a degree in accounts.
baseurl: "" # for GitHub Pages
url: "https://amcbhome.github.io"
theme: jekyll-theme-cayman

markdown: kramdown

