title: Alastair McBride
email: amcb.home@gmail.com
description: >
  CV and portfolio
baseurl: "" # for GitHub Pages
url: "https://amcbhome.github.io"
remote_theme: pages-themes/slate@v0.2.0
markdown: kramdown


