title: Alastair McBride
email: amcb.home@gmail.com
description: >
  CV and portfolio
baseurl: "" # for GitHub Pages
url: "https://amcbhome.github.io"

markdown: kramdown
theme: jekyll-theme-minimal

# Additional settings
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"



